language: ruby
cache: bundler
rvm:
- 2.1.0
- 2.0.0
- 1.9.3
notifications:
  email: false
  irc:
    channels:
    - secure: TDbNpHl7koTSkzDbtKwTRaxIZWl5W8C6vZGqjhQn3eltVokPzReiipQGpNhpUiGiBiO+80AFlEZs2Vc9smTAoTR4LP4jsC4so5fmYV2tS62xOGlVac/K3LcQDVRh9qXcjSt4BA68rsBENuYopVTTdwZE3exY/itE0xrbq3T1MNM=
    template:
    - "%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}"
